const CLEAR_REQUESTS = 'CLEAR_REQUESTS';
const INITIALIZE = 'INITIALIZE';
const RESET_MESSAGES = 'RESET_MESSAGES';
const RESET_RESPONSE = 'RESET_RESPONSE';
const SET_RESPONSE = 'SET_RESPONSE';
const SET_SIMULATOR_LIST = 'SET_SIMULATOR_LIST';
const STORE_MESSAGE = 'STORE_MESSAGE';
const STORE_REQUEST = 'STORE_REQUEST';

module.exports = {
  CLEAR_REQUESTS,
  INITIALIZE,
  RESET_MESSAGES,
  RESET_RESPONSE,
  SET_RESPONSE,
  SET_SIMULATOR_LIST,
  STORE_MESSAGE,
  STORE_REQUEST
};
