const CLEAR_REQUESTS = 'CLEAR_REQUESTS';
const HIDE_MODAL = 'HIDE_MODAL';
const INITIALIZE = 'INITIALIZE';
const RECEIVE_SOCKET_MESSAGE = 'RECEIVE_SOCKET_MESSAGE';
const RESET_MESSAGES = 'RESET_MESSAGES';
const RESET_RESPONSE = 'RESET_RESPONSE';
const SET_ACTIVE_SOCKET_CONNECTIONS = 'SET_ACTIVE_SOCKET_CONNECTIONS';
const SET_MESSAGE_LIST = 'SET_MESSAGE_LIST';
const SET_REQUEST_LIST = 'SET_REQUEST_LIST';
const SET_RESPONSE = 'SET_RESPONSE';
const SET_SIMULATOR_LIST = 'SET_SIMULATOR_LIST';
const SHOW_MODAL = 'SHOW_MODAL';
const STORE_MESSAGE = 'STORE_MESSAGE';
const STORE_REQUEST = 'STORE_REQUEST';

module.exports = {
  CLEAR_REQUESTS,
  HIDE_MODAL,
  INITIALIZE,
  RECEIVE_SOCKET_MESSAGE,
  RESET_MESSAGES,
  RESET_RESPONSE,
  SET_ACTIVE_SOCKET_CONNECTIONS,
  SET_MESSAGE_LIST,
  SET_REQUEST_LIST,
  SET_RESPONSE,
  SET_SIMULATOR_LIST,
  SHOW_MODAL,
  STORE_MESSAGE,
  STORE_REQUEST
};
